version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prueba
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: postgres
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
